$MINGW_PACKAGE_PREFIX=$env:MINGW_PACKAGE_PREFIX

$env:MSYS2_PACKAGES = "$env:MSYS2_PACKAGES
base-devel
autotools
cmake
python
gcc
gdb
xmlto
autogen
intltool
help2man
vim
scons
swig
asciidoc
patchutils
pkgfile
pcre
pcre2
windows-default-manifest
gettext-devel
libiconv-devel
man-db
quilt
unrar
reflex
libunrar-devel
btyacc
${MINGW_PACKAGE_PREFIX}-cmake
${MINGW_PACKAGE_PREFIX}-gdb
${MINGW_PACKAGE_PREFIX}-gdb-multiarch
${MINGW_PACKAGE_PREFIX}-libuv
${MINGW_PACKAGE_PREFIX}-spirv-tools
${MINGW_PACKAGE_PREFIX}-lld
${MINGW_PACKAGE_PREFIX}-mosquitto
"