$MINGW_PACKAGE_PREFIX=$env:MINGW_PACKAGE_PREFIX

# make depends
$env:MSYS2_PACKAGES = "$env:MSYS2_PACKAGES
${MINGW_PACKAGE_PREFIX}-asciidoc
${MINGW_PACKAGE_PREFIX}-cc
${MINGW_PACKAGE_PREFIX}-gobject-introspection
${MINGW_PACKAGE_PREFIX}-gtk-doc
${MINGW_PACKAGE_PREFIX}-luajit
${MINGW_PACKAGE_PREFIX}-pkgconf
${MINGW_PACKAGE_PREFIX}-ruby
${MINGW_PACKAGE_PREFIX}-vala
${MINGW_PACKAGE_PREFIX}-meson
${MINGW_PACKAGE_PREFIX}-openmp"

# depends
$env:MSYS2_PACKAGES = "$env:MSYS2_PACKAGES
${MINGW_PACKAGE_PREFIX}-babl
${MINGW_PACKAGE_PREFIX}-cairo
${MINGW_PACKAGE_PREFIX}-exiv2
${MINGW_PACKAGE_PREFIX}-ffmpeg
${MINGW_PACKAGE_PREFIX}-gexiv2
${MINGW_PACKAGE_PREFIX}-gcc-libs
${MINGW_PACKAGE_PREFIX}-gdk-pixbuf2
${MINGW_PACKAGE_PREFIX}-gettext
${MINGW_PACKAGE_PREFIX}-glib2
${MINGW_PACKAGE_PREFIX}-jasper
${MINGW_PACKAGE_PREFIX}-json-glib
${MINGW_PACKAGE_PREFIX}-libjpeg
${MINGW_PACKAGE_PREFIX}-libpng
${MINGW_PACKAGE_PREFIX}-libraw
${MINGW_PACKAGE_PREFIX}-librsvg
${MINGW_PACKAGE_PREFIX}-libspiro
${MINGW_PACKAGE_PREFIX}-libwebp
${MINGW_PACKAGE_PREFIX}-lcms
${MINGW_PACKAGE_PREFIX}-lensfun
${MINGW_PACKAGE_PREFIX}-maxflow
${MINGW_PACKAGE_PREFIX}-openexr
${MINGW_PACKAGE_PREFIX}-pango
${MINGW_PACKAGE_PREFIX}-SDL2
${MINGW_PACKAGE_PREFIX}-suitesparse"
