$MINGW_PACKAGE_PREFIX=$env:MINGW_PACKAGE_PREFIX

# make depends
$env:MESA_PACKAGES = "$env:MESA_PACKAGES
${MINGW_PACKAGE_PREFIX}-cc
${MINGW_PACKAGE_PREFIX}-glslang
${MINGW_PACKAGE_PREFIX}-flex
${MINGW_PACKAGE_PREFIX}-bison
${MINGW_PACKAGE_PREFIX}-python-mako
${MINGW_PACKAGE_PREFIX}-meson
${MINGW_PACKAGE_PREFIX}-pkgconf
${MINGW_PACKAGE_PREFIX}-libelf"

# depends
$env:MESA_PACKAGES = "$env:MESA_PACKAGES
${MINGW_PACKAGE_PREFIX}-llvm
${MINGW_PACKAGE_PREFIX}-clang
${MINGW_PACKAGE_PREFIX}-libclc
${MINGW_PACKAGE_PREFIX}-libva
${MINGW_PACKAGE_PREFIX}-spirv-tools
${MINGW_PACKAGE_PREFIX}-spirv-llvm-translator
${MINGW_PACKAGE_PREFIX}-vulkan-loader
${MINGW_PACKAGE_PREFIX}-zlib
${MINGW_PACKAGE_PREFIX}-zstd"

# optdepends
$env:MESA_PACKAGES = "$env:MESA_PACKAGES
${MINGW_PACKAGE_PREFIX}-opengl-man-pages
${MINGW_PACKAGE_PREFIX}-vulkan-validation-layers
"
